### ISSUE TITLE
No scaling, or incorrect scaling using cartogram

### ISSUE THREAD

**Issue by flashton2003** [sjewo/cartogram#16]
Thanks for making the cartogram package available. I'm trying to make a cartogram of TB burden in Africa (the whole world is my goal, Africa just a stepping stone) and the cartogram is giving output which does not scale by the burden. The range of TB burden is about 438000 to 0. The output for this, run with 500 iterations is below, the problem is that there is no scaling of the country area by TB burden:

![rplot01](https://user-images.githubusercontent.com/2613906/44571799-0979f080-a7ac-11e8-872e-abd30f124d61.jpeg)

Here is the code I used to generate this:

```
library(readr)
library(cartogram)
library(tmap)
library(maptools)

data(wrld_simpl)

tb_burden <- read_delim("~/Dropbox/mtb/tb_burden_stats/tb_cartogram/tb_burden.tsv", "\t", escape_double = FALSE, trim_ws = TRUE)
wrld_tb <- merge(wrld_simpl, tb_burden, by.x = "NAME", by.y = 'Rcountry')
afr_tb <- wrld_tb[wrld_tb$REGION == 2, ]
afr_tb <- spTransform(afr_tb, CRS("+init=epsg:3395"))
afr_tb_cont <- cartogram_cont(afr_tb, "TB_cases", itermax = 500)
#afr_tb_cart <- cartogram_cont(afr_tb, "POP2005", itermax = 1)
tm_shape(afr_tb_cont) + tm_polygons("TB_cases", style = "jenks") + tm_layout(frame = FALSE)
```

And a link to the [tb_burden.tsv](https://www.dropbox.com/s/dbb8czwdstbetml/tb_burden.tsv?dl=0) for replication.

I have also tried dividing the TB burden by 1000, with the same results. I [log transformed](https://www.dropbox.com/s/e89k3n83t2klcvd/log_tb_burden.tsv?dl=0) the TB burden, which gave this result, which doesn't make sense because South Africa and Nigeria should be largest (highest burden):

![untitled picture](https://user-images.githubusercontent.com/2613906/44571957-9755db80-a7ac-11e8-997e-c9420ca30035.png)

Any help would be greatly appreciated.

**Comment by Nowosad** [comment]
@sjewo It looks that the issue is caused by zeros in the dataset. It works well when all the values are > 0:

```r
afr_tb$TB_cases <- afr_tb$TB_cases + 1
afr_tb_cont <- cartogram_cont(afr_tb, "TB_cases", itermax = 10)
tm_shape(afr_tb_cont) + tm_polygons("TB_cases", style = "cont") + tm_layout(frame = FALSE)
```

![](https://i.imgur.com/GuU3pOz.png)

**Comment by flashton2003** [comment]
Thank you!

**Comment by flashton2003** [comment]
This is the first time in my experience that countries having no TB was a bad thing :-)

Thanks for the explanation.

**Comment by sjewo** [comment]
Your example is a tough problem for the algorithm: Canada and Greenland have the largest areas and a rather small population. The great number of fjords and islands aren't helpful either...

After 100 iterations the scaling looks a little bit better:
![ameri](https://user-images.githubusercontent.com/2435621/50773394-0f6efa80-1291-11e9-86da-9a7f77ede33f.png)

Maybe you could try another distortion algorithm, like this ArCGIS plugin: https://www.arcgis.com/home/item.html?id=d348614c97264ae19b0311019a5f2276
