### ISSUE TITLE
Dorling Cartogram

### ISSUE THREAD

**Issue by sjewo** [sjewo/cartogram#2]
Add  Dorling Cartograms

**Comment by rCarto** [comment]
Hi @sjewo , can you have a look at this implementation of dorling cartograms : https://gist.github.com/rCarto/3e1695c358cb898ad3fc6b939b875a7b ? If you are ok to add it in `cartogram`, I have a PR ready in my fork. The major change for the package would be to add [packcircles](https://github.com/mbedward/packcircles) in Imports. 

![rplot](https://user-images.githubusercontent.com/3041254/41358360-847be89a-6f28-11e8-9856-eb8213e650ab.png)


I have tried to adapt @hrbrmstr [spdorling](https://github.com/hrbrmstr/spdorling) package first (to allow `sf` input/output and use `sf` internaly) (see https://gist.github.com/rCarto/372977dd59f64b91b7e2b3e512ada159). But the solution with packcircles is much faster and IMO more configurable (see the `weights` argument).

Let me know.

**Comment by hrbrmstr** [comment]
this is way cool!

**Comment by sjewo** [comment]
Hi @rCarto , this would be a great addition to the package!

I'll have a look at your code this weekend.

**Comment by sjewo** [comment]
Hi @rCarto !

Thanks for your pull request - I think adding `packcircles` should be fine.
