### ISSUE TITLE
cartogram_cont with sf not working correctly

### ISSUE THREAD

**Issue by neuwirthe** [sjewo/cartogram#20]
cartogram_cont with sf polygons does not work.
The enclosed file demonstrates that. It contains 16 polygons, the resizing variable
has 8 values of 100 and 8 values of 1000, but the polygons are not resized accordingly.

[cartobug.R.zip](https://github.com/sjewo/cartogram/files/3020427/cartobug.R.zip)

**Comment by sjewo** [comment]
Thanks for the report! I figured out `cartogram_cont` will fail if the map is not projected. Reprojection will help until this issue is fixed:  
```
incarto_carto <- cartogram_cont(st_transform(incarto, 25832),"Size") 
```

**Comment by neuwirthe** [comment]
My solution was to do
sf_object %>% as_Spatial() %>% cartogram(...) %>% st_to_sf() %>%

**Comment by neuwirthe** [comment]
I just noticed that I had a typo in my suggestion:

`sf_object %>% as_Spatial() %>% cartogram(...) %>% st_as_sf() %>%`

is what it should be.

**Comment by sjewo** [comment]
Some steps in the calculation of the distortion require projected coordinates, thus starting with 0.2.0 cartogram will give an error for long lat coordinates.
