### ISSUE TITLE
Cartogram rendering bug that depends on number of iterations

### ISSUE THREAD

**Issue by binkleym** [sjewo/cartogram#25]
I wrote a R script to render a cartogram weighted by population.   I noticed that, for whatever reason, it wasn't filling in Colorado.   When I started debugging it, I found that the bug was iteration-dependent.   6 iterations or less, it works fine.  7 or more, and it won't fill Colorado's color appropriately.

I have tested this on R 2.6.1 running RStudio Server 1.2.5019, using Cartogram 0.2.0.    Server is Ubuntu Eoan 64 bit.   Let me know if there's any other useful debugging info you might want.

Graph that shows the bug in action (look at Colorado in the cartogram):
https://i.imgur.com/ujd8NFD.png

R script to render the above graph:
https://pastebin.com/BzVafJVA

The R script needs some .csv data to render the map.   Download the data from the Pastebin below and save as "cartogram-bug-data.csv"
https://pastebin.com/a5N4JAwL

**Comment by sjewo** [comment]
Thanks for open this issue!

In 'cartogram_cont' the values of the weighting variable are adjusted by default to reach convergence earlier. It seems, that in your example the adjustment leads to a unwanted effect and shrinks Colorado to a very small area.

You might disable the adjustment with option 'prepare="none"'.

```
us_map_cartogram <- us_map %>%
                      st_transform(crs = 2163) %>%
                      cartogram_cont("pop2020", 
                                     itermax = 25, 
                                     prepare="none")
```

![unemp](https://user-images.githubusercontent.com/2435621/72797955-53d1fc00-3c42-11ea-8dfc-75fac5b52a32.png)

**Comment by binkleym** [comment]
Thanks!   I can confirm that the prepare = "none" option does fix the problem.
