### ISSUE TITLE
Not working with EPSG:4326 or EPSG:4269

### ISSUE THREAD

**Issue by mike-duran-mitchell** [sjewo/cartogram#29]
I have a MULTIPOLYGON dataframe from sf with ~70 rows that is telling me it is not projected when using 4326 or 4269. When i run either of these:

```
cartogram::cartogram_cont(kuldorff_cluster %>% st_as_sf() %>% 
                             st_set_crs(4326) %>% 
                             st_transform(crs = 4326),
                              "point_count")

cartogram::cartogram_cont(kuldorff_cluster %>% st_as_sf() %>% 
                            st_set_crs(4269) %>% 
                            st_transform(crs = 4269),
                             "point_count")
```
They return the classic error:
```
Error: Using an unprojected map. This function does not give correct centroids and distances for longitude/latitude data:
Use "st_transform()" to transform coordinates to another projection.
```

However, I can change that to the vast majority of other EPSG projections (any random one that i tried, including those that don't include the extent of my data in West Georgia; for instance, I tried 3435 for Chicago where none of my data lies) and it does not give me that error:
```
cartogram::cartogram_cont(kuldorff_cluster %>% st_as_sf() %>% 
                            st_set_crs(2240) %>% 
                            st_transform(crs = 2240),
                             "point_count")
```
or even something less consistent like:
```
cartogram::cartogram_cont(kuldorff_cluster %>% st_as_sf() %>% 
                            st_set_crs(4326) %>% 
                            st_transform(crs = 2240),
                             "point_count")
```
and I get the expected output:
```
Mean size error for iteration 1: 2.95690459216305
Mean size error for iteration 2: 2.44362237184121
Mean size error for iteration 3: 2.03418172383997
Mean size error for iteration 4: 1.72093347562088
Mean size error for iteration 5: 1.49380990455156
Mean size error for iteration 6: 1.3355152500335
Mean size error for iteration 7: 1.22823616868653
Mean size error for iteration 8: 1.15650718125017
Mean size error for iteration 9: 1.10892367482285
Mean size error for iteration 10: 1.07716588358381
Mean size error for iteration 11: 1.0560339600933
Mean size error for iteration 12: 1.04142307853321
Mean size error for iteration 13: 1.03121208240042
Mean size error for iteration 14: 1.02442105200102
Mean size error for iteration 15: 1.01937143463375
```

Is there a reason that it doesn't work with 4326/4269? Or am I doing something incorrect here? Thanks.

**Comment by mike-duran-mitchell** [comment]
I now understand 4326/4269 are not projections but coordinate systems, but it doesn't appear that way from docs at places like: https://spatialreference.org/ref/epsg/4326/

**Comment by sjewo** [comment]
Hi Mike,

thanks for your question! You're right: EPSG:4326 and EPSG:4269 are coordinate systems representing coordinates in form of longitude/latitude degrees. The `cartogram` package can't handle these projections at the moment (this would require additional internal functions). 
The function only checks if the projection uses feet or meter as unit, not if its the best choice for your data.

I would like to suggest to transform your map into projections like EPSG:26967 (NAD83 / Georgia West) or EPSG:26717 (NAD27 / UTM zone 17N).
