### ISSUE TITLE
Non Contiguous Cartogram (Olson)

### ISSUE THREAD

**Issue by rCarto** [sjewo/cartogram#3]
Hello, 
We (@neocarto and I) have written an implementation of non-contiguous cartograms in a fork of your repo (https://github.com/riatelab/cartogram). 
I can make a pull request if you are interested.

**Comment by sjewo** [comment]
Looks great! I would be happy about a pull request. 

One option is to make "cartogram" a wrapper function and add a `type` option for different types of cartograms. 
Another is to stay with individual function like `cartogram_continuous` or `cartogram_noncontinuous`

**Comment by rCarto** [comment]
I would go for the 2nd option as different cartogram functions will have different sets of arguments. 
It would also be easier to document each method in a separate function.
