### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mtennekes** [sjewo/cartogram#5]
```
library(tmap)
install_github("sjewo/cartogram")
library(cartogram)

# Example
data(NLD_prov)
NLD_prov.carto <- cartogram(NLD_prov, "population", 5)
```

gives

```
Mean size error for iteration 1: 1.85185483178002
Error in get("rgeos", envir = .MAPTOOLS_CACHE) : object 'rgeos' not found
```

However, it works after loading `maptools`. Do you require `maptools`?

**Comment by sjewo** [comment]
oops! I made the package to depend on maptools and it should work now.

**Comment by mtennekes** [comment]
Tnx! Not really happy that maptools has to be in depends rather than suggests. As a consequence, each package that uses cartogram (e.g. tmap) should place it in depends to get it work. Maybe there is a workaround possible, e.g. to create the environment .MAPTOOLS_CACHE ourselves.

**Comment by sjewo** [comment]
I looked into maptools R code and it is probably the best to copy code for the 'checkPolygonHoles' function to cartogram. The function relies only on rgeos, so maptools is not needed.

**Comment by mtennekes** [comment]
Nice solution!
