### ISSUE TITLE
Cartograms extremely slow

### ISSUE THREAD

**Issue by popovs** [sjewo/cartogram#7]
Hopefully it's just something wrong with my code that I can fix, but it may be an issue with `cartogram`. The cartograms I'm making are here: https://github.com/popovs/400m-cartograms

Each iteration of the cartogram is taking me about 1 minute, and I don't get significant warping in my cartos unless I do at a minimum 50 iterations.

**Comment by sjewo** [comment]
Hi there,

your map is very detailed, so it slows the algortihm down. Using a less detailed map will speed things up:

```
# world map from tmap package
data(World, package="tmap")
wo <- gSimplify(World, 10000)
wrld_simpl <- SpatialPolygonsDataFrame(wo, World@data, match.ID=F)

world <- wrld_simpl[wrld_simpl$name != "Antarctica",c("iso_a3", "name", "continent")] # World GIS SpatialPolygonsDataFrame (spdf) from base R, minus Antarctica, minus irrelevant columns (hopefully subregion is actually irrelevant loooool)

names(world) <- c("ISO3", "NAME", "REGION")
```

You could additionally try the "parallel" branch of cartogram on github. Its fairly untested, but might be faster too.

**Comment by popovs** [comment]
Thanks for the suggestion! 

This isn't quite an 'issue' so I didn't want to create another one, but do you think you will be able to implement alternative cartogram algorithms into this? Eg., Gastner & Newman (2004)?

**Comment by sjewo** [comment]
I am planning to add new algorithms some time, but this will take some time.
