### ISSUE TITLE
The **sf** support

### ISSUE THREAD

**Issue by Nowosad** [sjewo/cartogram#8]
@sjewo Do you plan to add a support for **sf** objects in the near future? 

One of sections in our forthcoming book "Geocomputation with R" - https://geocompr.robinlovelace.net/adv-map.html#pseudo-unusual-maps - is going to show some examples of less usual types of maps. I enjoy the **cartogram** package and therefore, I think that use of this package could be one of the examples.

**Comment by sjewo** [comment]
@Nowosad That is a good question. The support of sf object in the cartogram algorithm should be fairly easy, but there are some other **sp** and **rgeos** functions needed and I need to search for a **sf** equivalent. 

Another option is to write an **sf**-method and convert the **sf** object to **sp**.

I will make myself more familiar with the sf classes and give you an update on this issues in the next days.

**Comment by Nowosad** [comment]
The migrating page could be useful in this case - https://github.com/r-spatial/sf/wiki/Migrating.

**Comment by sjewo** [comment]
Thanks for the link - really helpful! 

I added a method for sf-object to cartogram in the "sf" branch: b81b8f956bcc313e8dffcf88b76c0c8723d785c6

*cartogram* will work on sf-objects, but the code is really slow (probably due to the object creation in the call of *st_distance*).

**Comment by sjewo** [comment]
@Nowosad I will make a CRAN release after I finished the sf-method for the nc_cartogram function.

**Comment by Nowosad** [comment]
Great.

**Comment by Nowosad** [comment]
https://cran.r-project.org/web/packages/cartogram/index.html - close?
